### ISSUE TITLE
Unable to save diagram ("There currently is no content on the canvas")

### ISSUE THREAD

**Issue by elca-maxime-gamboni** [WPS/domain-story-modeler#121]
Hello,

I have a diagram with a dozen items in the local modeler (i.e. URL is `file:///.../index.html`). I originally opened a diagram made by someone else with the "Import story from file" button, made some changes, and when trying to save with the "Export story as .dst file", Domain Story Modeller pops a dialog saying that "There currently is no content on the canvas. Without content the canvas cannot be exported."

Export as png works fine, but I would like to keep my changes in case I need to make further changes in the future.

I'm using version 1.3.1 on Firefox 103.0.1 on Windows.

Is there a way (maybe by typing some commands in the JS Console) I could recover the diagram? I've been saying "No" to Firefox AND Windows both wanting to restart for upgrades for now, but I will have to close the browser at some point :)

Thank you!

**Comment by AlexanderZellober** [comment]
This seems like a genuine Bug.
Does the svg-export work? 
The .dst.svg-file also contains the domain-story and can be used in the import instead tof the .dst file.

**Comment by elca-maxime-gamboni** [comment]
Ok that's interesting. SVG export works (😊). But when I open that SVG in (another) Domain Story Modeller I get a blank page with just the title (😔)

**Comment by AlexanderZellober** [comment]
DId you locally install via npm install or via npm ci?

The underlying Framework we use has changed their elementRegistry by introducing a new Layer between the root and the actual diagram in a patch-version.
Due to the breaking-change being in a patch versione, depending how the npm-packages were installed, there is a problem during the fetching of the model for exporting.
Unfortunately this affects all versions of the modeler, since we cannot change the versionNumber to be exact post-release.

I do not think, that in this case it is possible to extract the domainstory from the elementregistry due to this error.
You can try to extract it via the browser debugger in the file canvasElementRegistry and reading out elementRegistry, but that might already be broken.

**Comment by elca-maxime-gamboni** [comment]
I downloaded the .zip from here: https://github.com/WPS/domain-story-modeler/releases , and unpacked it. I did not use npm at any point.

**Comment by AlexanderZellober** [comment]
The release then seems to have an error. 
I will talk with @hschwentner, and we will release a new patch-version with the correct packages.

For now I would reccomend using the 1.3.0 release-version. The only difference is the toggle for png and svg-export to export without the title of the domainstory.

**Comment by elca-maxime-gamboni** [comment]
Ok thank you!

Probably we keep this issue open then, until you release a patch?

**Comment by AlexanderZellober** [comment]
Will do
We also updated the zip-File in the release with the correctly build version to avoid this error in the future
