### ISSUE TITLE
export story does not save arrows and main title

### ISSUE THREAD

**Issue by kuerm** [WPS/domain-story-modeler#19]
It looks like it's only possible to open the conversation icon with text after saving and reopening.

PS: thanks for your presentations at TAG 2018

**Comment by hofstef** [comment]
Hi, can you please provide more details? Browser, modeler version, screenshots and if possible the exported file? Thank you!

**Comment by kuerm** [comment]
Firefox 62.0.3
Domainstorymodeler v0.3.0

[test.txt](https://github.com/WPS/domain-story-modeler/files/2502265/test.txt) (txt => dst)
![grafik](https://user-images.githubusercontent.com/28057122/47305949-5bfc4f80-d62b-11e8-9818-ba451354987f.png)

Reproducing wasn't possible the easy way. A dummy story worked. So I had to replace the texts by some random a's in my original file that didn't work.

**Comment by hofstef** [comment]
Sorry, but we were not able to reproduce the behaviour or analyze the root cause of the problem. Please let us know if the problem occurs again and what steps are necessary to reproduce it. If possible provide the output from your browser's error console (Chrome: hit F12 and open the "Console" tab).

**Comment by superloop** [comment]
Hey, just encountered the same problem with version 0.5.0-dev. When trying to import a saved model again, my browser console shows this:
```
index.js:84 Uncaught TypeError: Cannot read property 'parent' of undefined
    at DomainStoryModeler._addCustomConnection (index.js:84)
    at Array.forEach (<anonymous>)
    at DomainStoryModeler.addCustomElements (index.js:130)
    at DomainStoryModeler.importCustomElements (index.js:97)
    at FileReader.reader.onloadend (app.js:398)
DomainStoryModeler._addCustomConnection @ index.js:84
DomainStoryModeler.addCustomElements @ index.js:130
DomainStoryModeler.importCustomElements @ index.js:97
reader.onloadend @ app.js:398
FileReader (async)
document.getElementById.onchange @ app.js:403
```

**Comment by hofstef** [comment]
Thank you, @superloop that helps us a lot. Any chance you can provide the .dst file that produced the error? (Github does not allow to upload .dst files, please rename it to .txt).

**Comment by superloop** [comment]
Sure. After having removed the actual domain knowledge, the error is still there. I saved the model after having created 6 activities. When i open the file, it's just one activity being left. Hope this helps, because with this error i cannot use your great piece of software for actual work, which is quite sad.
[test-story_2019-01-22.txt](https://github.com/WPS/domain-story-modeler/files/2782747/test-story_2019-01-22.txt)
