### ISSUE TITLE
Multi-User Collaboration

### ISSUE THREAD

**Issue by InfoSec812** [WPS/domain-story-modeler#66]
**Is your feature request related to a problem? Please describe.**
It would be extremely valuable if multiple users could collaborate on the same model from different computers.

**Describe the solution you'd like**
Ideally, it would allow for a unique ID URL for each user and use a capability like WebRTC to synchronize state for all participants

**Describe alternatives you've considered**

**Additional context**

**Comment by hofstef** [comment]
I think there are two ideas in this request:

1. exchange a model more easily by providing a persistent URL; that was described by another user in #68

2. provide a collaborative modeling experience e.g. like miro.com so that multiple users can edit the same model simultaneously. We have no plans to take the modeler into that direction for these reasons:

- Domain Storytelling has always been a moderated workshop format. I think most people use it that way, so I think a collaboration feature would only be useful to few users.
- When Domain Storytelling is opened up to allow several modelers, virtual collaboration is i.m.o. not a replacement for a real, physical whiteboard (or smartboard). Personally, I have used this open format for brainstorming processes on a whiteboard with one/very few people. After trying other online-versions of collaborative modeling approaches like EventStorming, I doubt that a miro.com-like experience would work for this kind of Domain Storytelling.
- Video-conferencing tools allow the moderators to share their screen and, with some tools, even allow others to take over keyboard and mouse control. A combination of video conferencing and #68 could cover a lot of use cases.
- And finally, it seems like a lot of work.

Therefore, I will close this request and tag it “won’t fix”.

**Comment by InfoSec812** [comment]
In light of the current situation around the global pandemic, I feel like this feature has become even MORE important!
