### ISSUE TITLE
Store PNG/SVG exports with inline DST file 

### ISSUE THREAD

**Issue by hschwentner** [WPS/domain-story-modeler#83]
**Is your feature request related to a problem? Please describe.**
When I use a SVG or PNG file that is an export of a domain story, I usually want to edit it later. In most cases I forgot where I stored the corresponding DST file or there never was one.

**Describe the solution you'd like**
I want to store the JSON from the DST file in the SVG/PNG file as well. This way, the picture files would become editable and everything would be in one place. 

**Additional context**
Draw.io uses a similar approach. In SVG the data is stored in a "content" attribute of the "svg" tag. The See JGraph/mxgraph.

**Comment by AlexanderZellober** [comment]
For SVG there is an implementation on FeatureTest

Exporting it to a PNG seems a bit tricky

**Comment by hofstef** [comment]
- starting with v1.2.0, exported SVG will containd embedded JSON (the .dst file). Hence, the file extension was changed from .svg to .dst.svg
  - in v1.2.0, .dst and .svg (with embedded JSON) can be importet. To give users more freedom to rename their files, we opted to set the file filter in the import dialog to .dst and .svg (rather than the more restrivtive .dst.svg)
  - in future versions, we might switch to .dst.svg as default export format (but keep .dst import for compatibility reasons)
- exported PNG do not yet contain embedded .dst JSON
