### ISSUE TITLE
The activity labels are not visible

### ISSUE THREAD

**Issue by JoThomsen** [WPS/domain-story-modeler#89]
Moin moin,

the labels for the activities on the arrows only appear once you have pressed the play button. 

**To Reproduce**
Create a simple story with at least one arrow.

**Expected behavior**
The activity lables are immediately visible on the arrows.

**Screenshots**
![image](https://user-images.githubusercontent.com/22983077/103873158-af093280-50cf-11eb-9b3b-7979d52aa212.png)

**Desktop (please complete the following information):**
 - Modeler Version: Domain Story Modeler v1.2.0-dev
 - Browser: Chrome  87.0
 - OS: Windows 10

**Comment by AlexanderZellober** [comment]
This Bug is related to a Chrome Bug https://bugs.chromium.org/p/chromium/issues/detail?id=1107442 and affects all Versions of the modeler and only occurs in Chrome v84.0 as far as I can tell.

Until the Bug is fixed in Chrome, I suggest using an alternate Browser or using the workaround of starting the replay as soon as the first activity with a number label is added.
Besides replaying a story, the activity numbers seem to be drawn when zooming. 

Afterwards the labels should be rendered correctly.

This Bug will be kept open for visibility

**Comment by AlexanderZellober** [comment]
The Chrome Bug was fixed some time ago, thus this Bug will be closed
